
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage , filedialog , messagebox
from frame_utils import switch_frame
from SystemCode import MainSystem

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def get_Folder_Path():
    global folder_path
    folder_path = filedialog.askdirectory()
    print(folder_path)
    

def save_File():

    ms = MainSystem()

    try : 
       x , y =  ms.save_Data_To_CSV(folder_path)
       messagebox.showinfo("Saved" , message= f"Saved at {y}")
       switch_frame(f_frame)

    except:
        messagebox.showerror("Error" , message="Error while saving please try again !")

        

def save_Scene( main_frame , final_frame , back_frame):

    global f_frame

    f_frame = final_frame

    main_frame.tkraise()
   
    canvas = Canvas(
        main_frame,
        bg = "#0E0E0E",
        height = 620,
        width = 920,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        main_frame,
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command= save_File,
        relief="flat"
    )
    button_1.place(
        x=584.0,
        y=438.0,
        width=298.0,
        height=81.0
    )

    canvas.create_text(
        257.0,
        80.0,
        anchor="nw",
        text="Choose a folder to save the file in it !",
        fill="#FFFFFF",
        font=("Inter SemiBold", 28 * -1)
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        main_frame,
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command= get_Folder_Path,
        relief="flat"
    )
    button_2.place(
        x=311.0,
        y=228.0,
        width=298.0,
        height=87.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        main_frame,
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: switch_frame(back_frame),
        relief="flat"
    )
    button_3.place(
        x=46.0,
        y=438.0,
        width=298.0,
        height=81.0
    )
    
    main_frame.image_refs = [button_image_1, button_image_2, button_image_3]
